### ISSUE TITLE
 Label correction for Source Image transferred by the dual path image generation module.

### ISSUE THREAD

**Issue by willer94** [royee182/DPL#1]
Hi, thanks for the nice paper and clear code.
I have a simple quesetion about the source label correction. 
During the whole training process, it seems that only step 4.1 (in Single Path Warm-up) takes label correction for transferred source images.
I am wondering that if the labels should be adjusted after step 2 (Quick start for DPL training), since the Cycle GAN used here is different from the one used in the step 2 in Single Path Warm-up. It seems that the transferred source images are different from each other in aforementioned two steps.

Thanks a lot!

**Comment by royee182** [comment]
Yes, only step 4.1 (in Single Path Warm-up) takes label correction for transferred source images. 
In DPL training, since the issue of visual inconsistency is already alleviated by dual perceptual loss proposed in Dual Path Image Translation (DPIT), we no longer apply label correction for simplification.

**Comment by valencebond** [comment]
I also wonder why not use source label correction in Eq.8 as in Eq. 1. Is there any ablation study here? By the way, what are you mentioned "step2" or "step4.1" ? I can not find any ref in the code or the paper.

**Comment by royee182** [comment]
In the preliminary exploratory stage, we conduct ablation study with Single Path Image Translation(SPIT) module (refer to Table 1 in paper). Under the setting of GAT5->Cityscapes, Resnet101, the mIou of M_S^(0) are: 
- SPIT w/o label correction  48.6
- SPIT w/ label correction  47.7

We can observe that label correction leads to performance decline with SPIT module. The reason is that with perceptual loss, visual consistency is basically maintained in SPIT, the correction by model itself may introduce wrong revision. 
Refer to Table 1 in paper and Figure 7 in appendix, visual consistency is better ensured by Dual Path Image Translation (DPIT), so that label correction in our DPL with DPIT is also not suggested.
You can find "step2" and "step4.1" in readme doc of the code.
